### ISSUE TITLE
AWS Cognito Shibboleth IDP configuration

### ISSUE THREAD

**Issue by pwhite1975** [UWFosterIT/aws-cognito#1]
Hi, I am having problem with my IDP setup. I would appreciate if you can provide the sample of IDP settings so that I can get shibboleth working with AWS Cognito.

Thanks
Paul

**Comment by kevintechie** [comment]
Hi Paul, 
Unfortunately, we can't provide support for installation and configuration of Shibboleth. If you have questions about our example aws-cognito code, I'm happy to help.

**Comment by rogerskk** [comment]
Just for anyone else this might help, Shibboleth was returning a string longer than 128 characters for UserID that was throwing the error.  It was returning a transient id instead of a persistent id.  We were able to change it to return the netid as the UserId as the persistent id and that worked.
